export const LITERALS = {
  USER_NOT_FOUND: "User not found.",
  USER_LOGOUT: "Session finished.",
  RESET_PASSWORD_SENT: "Reset password email sent successfully",
  USED_PASSWORD_ERROR: "You must define a password not used before.",
  PASSWORD_RESET: "Password reset successfully",
  PERMISSION_CREATED: "Permission created successfully",
  PERMISSIONS_FOUND_LENGTH: "%s permissions found",
  PERMISSION_NOT_FOUND: "Permission not found",
  PERMISSION_UPDATED: "Permission updated succesfully",
  ASSOCIATED_PERMISSION_ERROR: "This permission is associated to active roles. Unassign this permission from roles before deleting.",
  PERMISSION_DELETED: "Permission deleted succesfully",
  ROLE_WITHOUT_PERMISSION: "Role must contains at least one permission.",
  ROLE_CREATED: "Role created successfully",
  ROLES_FOUND_LENGTH: "%s roles found",
  ROLE_NOT_FOUND: "Role not found",
  ROLE_UPDATED: "Role updated succesfully",
  ROLE_ASSIGNED_ERROR: "This role is assigned to active users. Unassign this role from users before deleting.",
  ROLE_DELETED: "Role deleted succesfully",
  USER_NOT_VERIFIED: "Authentication failed. User not verified or inactive.",
  INCORRECT_PASSWORD: "Authentication failed. Incorrect password.",
  USER_CREATED: "User created successfully",
  USER_UPDATING_ERROR: "Error updating user",
  USER_UPDATED: "User updated succesfully",
  WRONG_VERIFICATION_TOKEN: "Wrong verification token",
  VERIFIED_ACCOUNT: "Account verified successfully",
  VALIDATION_FAILED: "Validaton failed",
  LIMIT_REACHED: "You reached the %s request limit in %s. Please try again later.",
  HEY_THERE: "Hey, there. I am Auth API!",
  NAME_FORBIDDEN: "This name is forbidden",
  INVALID_EMAIL_FORMAT: "Invalid email format",
  INVALID_PASSWORD_FORMAT: `Invalid password format: %s`,
}